# Generated by Django 5.2.7 on 2025-11-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_categorie_commande_plat_lignecommande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='image',
        ),
    ]
