# Generated by Django 5.2.7 on 2025-11-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_plat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plats/'),
        ),
    ]
