# Generated by Django 5.2.7 on 2025-11-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_plat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='points_gagnes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
