# Generated by Django 5.2.7 on 2025-12-05 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_commande_points_gagnes_profile_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(choices=[('serveur', 'Serveur/Serveuse'), ('cuisinier', 'Cuisinier'), ('chef', 'Chef de cuisine'), ('plongeur', 'Plongeur'), ('manager', 'Manager'), ('caissier', 'Caissier')], default='serveur', max_length=50)),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('interim', 'Intérim'), ('stage', 'Stage')], default='cdi', max_length=20)),
                ('date_embauche', models.DateField(default=django.utils.timezone.now)),
                ('salaire_horaire', models.DecimalField(decimal_places=2, default=12.0, max_digits=6)),
                ('heures_hebdomadaires', models.DecimalField(decimal_places=2, default=35.0, max_digits=5)),
                ('horaires', models.JSONField(blank=True, default=dict)),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=15, null=True)),
                ('telephone_urgence', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_urgence', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employe_info', to='restaurant.profile')),
            ],
            options={
                'verbose_name': 'Informations employé',
                'verbose_name_plural': 'Informations employés',
            },
        ),
    ]
